### ISSUE TITLE
Ik greeg een error toe in de code uitvoerde

### ISSUE THREAD

**Issue by NielzosFilmsSchool** [robinvanputten/Ooh-nee-origin-vergeten-8aa8eb66#1]
PHP Parse error:  syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in D:\Bit Academy\Nakijken\MyLogger.class.php on line 4

Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in D:\Bit Academy\Nakijken\MyLogger.class.php on line 4

**Comment by robinvanputten** [comment]
Dit bestand maakt gebruik van een typed property, [dat is een nieuwe feature van php 7.4](https://www.php.net/manual/en/migration70.new-features.php)
